### ISSUE TITLE
what is the supported platform for tensorflow-2.1.0-cp37-cp37m-linux_armv7l.whl 

### ISSUE THREAD

**Issue by javacom** [Qengineering/TensorFlow-Raspberry-Pi#1]
sudo -H pip3 install tensorflow-2.1.0-cp37-cp37m-linux_armv7l.whl
tensorflow-2.1.0-cp37-cp37m-linux_armv7l.whl is not a supported wheel on this platform.

I am using Raspberry pi 4B
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster

**Comment by Qengineering** [comment]
Probably you forgot to download the wheel from this site before installing. (?)
Please follow the instructions at https://qengineering.eu/install-tensorflow-2.1.0-on-raspberry-pi-4.html or https://qengineering.eu/install-tensorflow-2.2.0-on-raspberry-pi-4.html.
We have checked the procedure several times and encounter no problems with the installation.

**Comment by javacom** [comment]
```
pi@pi01:~/Projects $ gdown https://drive.google.com/uc?id=11mujzVaFqa7R1_lB7q0kVPW22Ol51MPg
Downloading...
From: https://drive.google.com/uc?id=11mujzVaFqa7R1_lB7q0kVPW22Ol51MPg
To: /home/pi/Projects/tensorflow-2.2.0-cp37-cp37m-linux_armv7l.whl
150MB [00:11, 13.0MB/s] 
pi@pi01:~/Projects $ sudo -H pip3 install tensorflow-2.2.0-cp37-cp37m-linux_armv7l.whl
tensorflow-2.2.0-cp37-cp37m-linux_armv7l.whl is not a supported wheel on this platform.
```

**Comment by Qengineering** [comment]
Very strange. With a clean Raspbian OS, we have no problems installing the wheel.
Do you have the latest pip3 (18.1), python3 (3.7.3) etc installed? According to this site it may generate the errors you have now. https://scottontechnology.com/solved-is-not-a-supported-wheel-on-this-platform/ 
See also tensorflow https://github.com/tensorflow/tensorflow/issues/9722

**Comment by javacom** [comment]
OK it is a pip3 version issue and upgraded solve my problem.

```
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python3 get-pip.py --force-reinstall
pip3 -V
python3 -m pip install --user tensorflow-2.1.0-cp37-cp37m-linux_armv7l.whl 

python3 tftest.py 
Hello, TensorFlow! 2.1.0
```
